# Через модули а не через пнп потому что вайт так и не завёлся через пнп
nodeLinker: node-modules

enableGlobalCache: false
cacheFolder: "./.yarn/cache"
cacheMigrationMode: "always"
deferredVersionFolder: "./.yarn/versions"
enableImmutableCache: false
